### ISSUE TITLE
Changing yellow color and brightness did not work for me

### ISSUE THREAD

**Issue by benedicte69** [material-components/material-components-flutter-codelabs#106]
In home.dart, change the brightness to dark
in login.dart, change the primary override to yellow for both text fields
When I did that it had no effect.
https://github.com/benedicte69/flutter_mdc_100_series

**Comment by johnsonmh** [comment]
Hi there, thanks for spotting this! The issue comes from the `PrimaryColorOverride` in `login.dart`. We're using `primaryColor` when we should be using `accentColor`.

I'm working on updating the code and docs, in the meantime, all you need to get it working is to change `primaryColor` to `accentColor` in the `build` method of `PrimaryColorOverride`.

See [pull 114](https://github.com/material-components/material-components-flutter-codelabs/pull/114/files) for more info.

**Comment by johnsonmh** [comment]
Codelab has been updated, as well as the code itself, to override the accentColor instead of the primaryColor. Thanks again for spotting this!

**Comment by benedicte69** [comment]
Hello MH Johnson,
Thank you for helping me but it is still not working, it seems impossible to override the first theme, am I forgetting to do something in app.dart?   Le jeudi 30 août 2018 à 19:21:56 UTC+2, MH Johnson <notifications@github.com> a écrit :  
 
 
Hi there, thanks for spotting this! The issue comes from the PrimaryColorOverride in login.dart. We're using primaryColor when we should be using accentColor.

I'm working on updating the code and docs, in the meantime, all you need to get it working is to change primaryColor to accentColor in the build method of PrimaryColorOverride.

See pull 114 for more info.

**Comment by benedicte69** [comment]
Thanks, but it is still not working even with accentColor, it seems impossible to override the first theme, am I forgetting to do something in app.dart?
   Le lundi 3 septembre 2018 à 17:21:21 UTC+2, Benedicte <notifications@github.com> a écrit :  
 
 Hello MH Johnson,
Thank you for helping me but it is still not working, it seems impossible to override the first theme, am I forgetting to do something in app.dart? Le jeudi 30 août 2018 à 19:21:56 UTC+2, MH Johnson <notifications@github.com> a écrit : 
 
 
Hi there, thanks for spotting this! The issue comes from the PrimaryColorOverride in login.dart. We're using primaryColor when we should be using accentColor.

I'm working on updating the code and docs, in the meantime, all you need to get it working is to change primaryColor to accentColor in the build method of PrimaryColorOverride.

See pull 114 for more info.

**Comment by johnsonmh** [comment]
Hi,

I tried cloning your repo at your latest commit, and I was actually able to get it working as intended. Just to clarify, what we are overriding is the color of the text field outline, only after the text field has been selected. 

![](http://i.imgur.com/9ed1XDf.png) 

Hope this helps, let me know if you have any more questions.

**Comment by benedicte69** [comment]
Hello MH Johnson,Thank you for your help but I am still in trouble with this subject  (The color you show me to override is the  textSelectionColor: kShrinePink100 ).
 In my app.dart, ThemeData my accentColor is kShrineBrown900. In my login.dart I am overriding this color to : color: kShrineAltYellow and no change occurs at all.   Le lundi 3 septembre 2018 à 21:04:04 UTC+2, MH Johnson <notifications@github.com> a écrit :  
 
 
Hi,

I tried cloning your repo at your latest commit, and I was actually able to get it working as intended. Just to clarify, what we are overriding is the color of the text field outline, only after the text field has been selected.



Hope this helps, let me know if you have any more questions.

**Comment by benedicte69** [comment]
Found something: in my app.dart I was on the first theme :) if I display the second theme in this file, the overriding works as expected and as you say!   Le mercredi 5 septembre 2018 à 11:47:42 UTC+2, Benedicte <notifications@github.com> a écrit :  
 
 Hello MH Johnson,Thank you for your help but I am still in trouble with this subject  (The color you show me to override is the  textSelectionColor: kShrinePink100 ).
 In my app.dart, ThemeData my accentColor is kShrineBrown900. In my login.dart I am overriding this color to : color: kShrineAltYellow and no change occurs at all. Le lundi 3 septembre 2018 à 21:04:04 UTC+2, MH Johnson <notifications@github.com> a écrit : 
 
 
Hi,

I tried cloning your repo at your latest commit, and I was actually able to get it working as intended. Just to clarify, what we are overriding is the color of the text field outline, only after the text field has been selected.



Hope this helps, let me know if you have any more questions.

**Comment by benedicte69** [comment]
Hello, Thank you for having taken the time to look at my GitHub. I have a last concerned, if I am using theme 01 the overriding does not work, if I am using theme 02, the overriding works. I have renamed the themes to clarify the situation but do not understand why it is only working if I am using theme number 02. Perhaps You can tell me. Thanks in advance.   Le mercredi 5 septembre 2018 à 12:14:02 UTC+2, Benedicte <notifications@github.com> a écrit :  
 
 Found something: in my app.dart I was on the first theme :) if I display the second theme in this file, the overriding works as expected and as you say! Le mercredi 5 septembre 2018 à 11:47:42 UTC+2, Benedicte <notifications@github.com> a écrit : 
 
 Hello MH Johnson,Thank you for your help but I am still in trouble with this subject  (The color you show me to override is the  textSelectionColor: kShrinePink100 ).
 In my app.dart, ThemeData my accentColor is kShrineBrown900. In my login.dart I am overriding this color to : color: kShrineAltYellow and no change occurs at all. Le lundi 3 septembre 2018 à 21:04:04 UTC+2, MH Johnson <notifications@github.com> a écrit : 
 
 
Hi,

I tried cloning your repo at your latest commit, and I was actually able to get it working as intended. Just to clarify, what we are overriding is the color of the text field outline, only after the text field has been selected.



Hope this helps, let me know if you have any more questions.

**Comment by benedicte69** [comment]
Hello, Thank you for having taken the time to look at my GitHub. I have a last concerned, if I am using theme 01 the overriding does not work, if I am using theme 02, the overriding works. I have renamed the themes to clarify the situation but do not understand why it is only working if I am using theme number 02. Perhaps You can tell me. Thanks in advance.

**Comment by johnsonmh** [comment]
Hm, I can't actually figure out what's going on. My original fix actually was not complete. It turns out that when our `ThemeData` (in `app.dart`) uses the `ThemeData.light()` theme as a base, the `TextField` border color is determined by `primaryColor`. But when we use the `ThemeData.dark()` theme as a base, the border color is determined by `accentColor`. 

@willlarche do you happen to know why this is?

**Comment by willlarche** [comment]
Don't know _why_ this is but accept that it is :) We've updated the code to use `accentColor`. Should be good to go.

**Comment by benedicte69** [comment]
It would be great to understand why too :) as very often I read some post such as:' when I make some change in Flutter, it does not display...' Clarifying the situation on where and how things are allocated could certainly solve some issues.
    Le lundi 10 septembre 2018 à 17:11:47 UTC+2, Will Larche <notifications@github.com> a écrit :  
 
 
Don't know why this is but accept that it is :) We've updated the code to use accentColor. Should be good to go.

**Comment by willlarche** [comment]
Oh, this isn't a case of technical mystery. If you follow the calls, you can find the code. https://github.com/flutter/flutter/blob/fc1b304326214296ac02bddfed9396e2a716e63d/packages/flutter/lib/src/material/input_decorator.dart#L1588

The mystery is why that logic is how it is. This was long before we had a Material Theming spec. So, the Flutter team had to make decisions. And they did a really great job. Material Theming ended up having different rules for text inputs but it came years later.
