### ISSUE TITLE
Mdc 102 flutter (Make a card collection step error)

### ISSUE THREAD

**Issue by arbaazaj** [material-components/material-components-flutter-codelabs#107]
In the home.dart file #Make a collection cards (102) on the line
**`List<Product> products = getProducts(Category.all);`**,

the **getProducts** method does not exists instead the correct code is 

**`List<Product> products = ProductsRepository.loadProducts();`** 

also don't forget to add **import 'model/products_repository.dart';**

**Comment by willlarche** [comment]
Hi! Thanks for flagging this issue.

The final line is actually kinda both put together. `List<Product> products = ProductsRepository.loadProducts(Category.all);`

The codelabs and this codebase have been updated.

**Comment by arbaazaj** [comment]
Your welcome :)
