### ISSUE TITLE
MDC-102 Flutter: Material Structure and Layout (Flutter) - Wrong function name.

### ISSUE THREAD

**Issue by rajeshzmoke** [material-components/material-components-flutter-codelabs#12]
**MDC-102 Flutter: Material Structure and Layout (Flutter)**

Fetching the product info with the wrong name **getAllProducts();**

`List<Card> _buildGridCards(BuildContext context) {
  List<Product> products = getAllProducts(); // **Wrong function name** 
...
...
}`

It should be 

` List<Product> products = getProducts(Category.all); `

**Comment by willlarche** [comment]
Great catch! It's been corrected in the document. Thank you so much for reporting it!! 🥇 

If you find more issues, please report them here!
If you have any other feedback, write to larche@google.com
