### ISSUE TITLE
Example code is missing previous changes

### ISSUE THREAD

**Issue by PieterAelse** [material-components/material-components-flutter-codelabs#122]
On page https://codelabs.developers.google.com/codelabs/mdc-104-flutter/index.html?index=..%2F..%2Findex#5 

The code block below the alinea 

> Change the _buildStack() function to take a BuildContext and BoxConstraints. Also, include a PositionedTransition that takes a RelativeRectTween Animation:

is missing the (previously changed) **ExcludeSemantics** wrap around the backlayer.

**Comment by michdud** [comment]
Thanks for reporting this! I've added the `ExcludeSemantics` widget back into the code snippet in the instructions. Let me know if this isn't the change you were thinking of!
