### ISSUE TITLE
Code styling incorrect in documentation

### ISSUE THREAD

**Issue by PieterAelse** [material-components/material-components-flutter-codelabs#123]
On page https://codelabs.developers.google.com/codelabs/mdc-104-flutter/index.html?index=..%2F..%2Findex#7  at the bottom, the last code block has the green "comment" code coloring continued for too long.

Screenshot:

![image](https://user-images.githubusercontent.com/6347879/44992934-0dbac080-af99-11e8-96aa-ab3dbbde1032.png)

**Comment by michdud** [comment]
Thanks for catching this! I've updated the code block so it doesn't have the comment color anymore.
