### ISSUE TITLE
lack definition to category in step 4 on MDC-104

### ISSUE THREAD

**Issue by jinksw** [material-components/material-components-flutter-codelabs#124]
under the section 'Remove the home app bar'
lack definition to category at home.dart which could cause a error when we have done the step 4 of MDC-104 .

there should be a `final Category category;` in the `HomePage` class

**Comment by jinksw** [comment]
actually it could not be a mistake If this step is not a hand by hand step.

**Comment by melorzhang** [comment]
> In home.dart, change the build() function to just return an AsymmetricView:
> 
> // TODO: Return an AsymmetricView (104)
> return  AsymmetricView(products: ProductsRepository.loadProducts(category));

should be 

> In home.dart, change the build() function to just return an AsymmetricView:
> 
> // TODO: Return an AsymmetricView (104)
> return  AsymmetricView(products: ProductsRepository.loadProducts(Category.all));

**Comment by willlarche** [comment]
This is fixed now. Thank you! Let me know if you still see a version that's wrong.
