### ISSUE TITLE
`titleSpacing` missing from the step 8 MDC-104 Flutter

### ISSUE THREAD

**Issue by idrakimuhamad** [material-components/material-components-flutter-codelabs#129]
On the 8th steps, we completed the "Add a branded icon". However, the menu and title seems to be a little bit pushed in from the left, to compare with the final example photo.

From the [codebase](https://github.com/material-components/material-components-flutter-codelabs/blob/104-complete/mdc_100_series/lib/backdrop.dart), there's the `titleSpacing: 0.0` in the `appBar` which did the trick.

**Comment by willlarche** [comment]
Thank you! Should be fixed now.
