### ISSUE TITLE
Documentation - Commands

### ISSUE THREAD

**Issue by Prathik-Jain** [material-components/material-components-flutter-codelabs#13]
In step 3 of MDC-101 : 
Command to clone from git repo : 
```bash
git clone 
https://github.com/material-components/material-components-flutter-codelabs.git
git checkout 101-starter
cd material-components-flutter-codelabs
```
**should be replaced with**

```bash
git clone \
https://github.com/material-components/material-components-flutter-codelabs.git
cd material-components-flutter-codelabs
git checkout 101-starter
```

**Comment by willlarche** [comment]
Great catch! Thank you so much. I've corrected the directory path. Are you sure the slash is needed after the `clone `? Is that just if there's a newline?

**Comment by Prathik-Jain** [comment]
Yup! that's for the new line - you can just move up the whole link if you want and a  _save a line_

**Comment by willlarche** [comment]
Should be good now. please verify. Reopen if not.
