### ISSUE TITLE
MDC-103: CutCornersBorder does not render anything

### ISSUE THREAD

**Issue by jdkoren** [material-components/material-components-flutter-codelabs#134]
From https://codelabs.developers.google.com/codelabs/mdc-103-flutter/#6

Using the `CutCornersBorder` in the `inputDecorationTheme` renders no border at all around the `TextInput`. It seems `CutCornersBorder` uses `BorderSide.none` by default; I resolved this with the following change:

In `CutCornersBorder` constructor:
```diff
 const CutCornersBorder({
-  BorderSide borderSide: BorderSide.none,
+  BorderSide borderSide: const BorderSide(),
   BorderRadius borderRadius: const BorderRadius.all(Radius.circular(2.0)),
   this.cut: 7.0,
   double gapPadding: 2.0,
 }
```

(Alternatively, one could pass a `BorderSide()` when constructing the `CutCornersBorder`, but I think the above change better supports the Principle of Least Surprise.)

Environment info
```
Flutter version 0.11.13 at path/redacted/flutter
Framework revision 58c8489fcd (4 days ago), 2018-11-29 19:20:18 -0500
Engine revision 7375a0f414
Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

Android Studio 3.4 Canary 6
Build #AI-183.4284.148.34.5146016, built on November 22, 2018
JRE: 1.8.0_152-release-1248-b01 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux (redacted)-amd64

Android Device: Pixel (sailfish) with Android 9.0
```

**Comment by willlarche** [comment]
Should be good to go on all branches. Thank you!
