### ISSUE TITLE
Typo in tests path

### ISSUE THREAD

**Issue by the1mattkaufman** [material-components/material-components-flutter-codelabs#14]
On page:
3. Download the codelab starter app

Step
4. In the project panel on the left, delete the testing file ../tests/widget_test.dart

The path is listed as "/tests/" but in the package itself, it is actually "/test/"

**Comment by willlarche** [comment]
Thank you! I think that has varied by Flutter version. Corrected!

And continue to write in with issues and feedback. We really appreciate it!!
