### ISSUE TITLE
MDC-102: (4) Add a top app bar, Add Actions, TODO

### ISSUE THREAD

**Issue by bdjidi** [material-components/material-components-flutter-codelabs#142]
Hello,

In the TODOs on page [4. Add a top app bar](https://codelabs.developers.google.com/codelabs/mdc-102-flutter/index.html?index=..%2F..index#3) the code listed simply states 

```dart
// TODO: Add trailing buttons (102)
fitWidth
```

where I believe it should read something like:

```dart
// TODO: Add trailing buttons (102)
actions: <Widget>[
  IconButton(
    icon: Icon(
      Icons.search,
      semanticLabel: 'search',
    ),
    onPressed: () {
      print('Search button');
    },
  ),
  IconButton(
    icon: Icon(
      Icons.tune,
      semanticLabel: 'filter',
    ),
    onPressed: () {
      print('Filter button');
    },
  ),
],
```

Thanks and great work on the series!

**Comment by PhillipMwaniki** [comment]
Haha, I was about to file this issue and you beat me to it

**Comment by willlarche** [comment]
Thank you for reporting that! It's been corrected. And thank you for your kind words! Let us know if anything else is awry.
