### ISSUE TITLE
Missing instructions for MDC-104, step 7 prevents filtering from working

### ISSUE THREAD

**Issue by alexandre-senecal** [material-components/material-components-flutter-codelabs#145]
The sample code to update home.dart does not pass category to the AsymetricView

> In home.dart, add a variable for Category and pass it to the AsymmetricView.
...
>   @override
>   Widget build(BuildContext context) {
>     // TODO: Pass Category variable to AsymmetricView (104)
>     return AsymmetricView(products: ProductsRepository.loadProducts(**Category.all**));
>   }
> }

Should be replaced with 

>   @override
>   Widget build(BuildContext context) {
>     // TODO: Pass Category variable to AsymmetricView (104)
>     return AsymmetricView(products: ProductsRepository.loadProducts(**category**));
>   }
> }

**Comment by rami-a** [comment]
Thanks for the opening the issue @alexandre-senecal, I have pushed up a change to the instructions with this fix. If you could please verify the fix, that would be great!

**Comment by alexandre-senecal** [comment]
Looks good! Thank you @rami-a
