### ISSUE TITLE
MDC-103 - Step 9 - buttonColor.

### ISSUE THREAD

**Issue by gushh** [material-components/material-components-flutter-codelabs#146]
Hi!
Following the instructions in step 9, the "next" button, of the login, does not change color correctly.

Inside `_buildShrineTheme()`, the code:
```
    buttonColor: kShrineAltYellow,
```

Produces:
![screenshot_1548759022](https://user-images.githubusercontent.com/4606232/51903409-d8c16700-239a-11e9-97ea-4160d5b5d22b.png)

Maybe should be changed by:
```dart
    buttonTheme: base.buttonTheme.copyWith(
      buttonColor: kShrineAltYellow,
      textTheme: ButtonTextTheme.primary,
    ),
```

Produces:
![screenshot_1548759098](https://user-images.githubusercontent.com/4606232/51903421-de1eb180-239a-11e9-9dab-a6002af68509.png)

Thanks for all, and excuse my limited English. :argentina: :v:

**Comment by rami-a** [comment]
Thanks for filing this issue, I have updated the docs to reflect this fix!
