### ISSUE TITLE
MDC-103 - Step 10 - Bad branch.

### ISSUE THREAD

**Issue by gushh** [material-components/material-components-flutter-codelabs#147]
Hi!
In the docs of step 10 I see that the branch name is wrong: 

> "The completed MDC-103 app is available in the _**104-starter_and_102-complete**_ branch.".

 This should be:
> "The completed MDC-103 app is available in the _**104-starter_and_103-complete**_ branch.".

Thanks for all. :argentina: :v:

**Comment by rami-a** [comment]
Thanks for filing this issue, I have updated the docs to reflect this fix!
