### ISSUE TITLE
confused sentence

### ISSUE THREAD

**Issue by ahan** [material-components/material-components-flutter-codelabs#148]
Doc: MDC-102 Flutter: Material Structure and Layout (Flutter)
Chapter: 6 - Make a card collection
Link: https://codelabs.developers.google.com/codelabs/mdc-102-flutter/index.html#5

Original: 
『You may notice we don't add any vertical space between the cards. That's because they have, by default, 4 points of padding on their top and bottom.』

The word 『vertical』 didn't match with 『top』 and 『bottom』.

I think maybe it means, 4 points of padding on their left and right, or horizontal with top and bottom?

**Comment by rami-a** [comment]
Thanks for filing this issue!

I think I may be misunderstanding the problem you are seeing. The sentence is explaining that since cards have 4 pts of padding on their top and bottom, that is what accounts for the vertical space between the cards. Does that make things clearer?

**Comment by ahan** [comment]
Thanks for explaining.
I got it.
