### ISSUE TITLE
MDC-104 - Step 4 - Remove the home app bar

### ISSUE THREAD

**Issue by boscowang** [material-components/material-components-flutter-codelabs#150]
AsymmetricView is undefined at MDC-104 - Step 4 if continuing from MDC-103.

1. hints for adding "import 'supplemental/asymmetric_view.dart';" in home.dart should also be included in MDC-104 - Step 4 - Remove the home app bar.
3. The import statement in home.dart should be removed from branch "104-starter_and_103-complete".

**Comment by rami-a** [comment]
In MDC-103 - Step 8, the import for asymmetric_view is included and so if continuing from MDC-103, you should have this import already there. Could you confirm that this is the case for you and add some more information if you are still running into this issue? Thanks

**Comment by boscowang** [comment]
No problem after redo MDC-103 step 8. I think i have reverted 1 extra step wrongly in home.dart after playing with the dark theme. Thanks.
