### ISSUE TITLE
description unclear on which code goes where

### ISSUE THREAD

**Issue by jayjtao** [material-components/material-components-flutter-codelabs#152]
Starting from MDC-102, some descriptions of which code goes where are unclear:

1. Writer(s) should refer to how StartupName did it
2. Writer(s) should check each code segments to make sure that location-wise are accurate
3. A simpler list of completed codes should be available for references

Thanks,
Jay

**Comment by willlarche** [comment]
Hi! Thank you so much for doing the codelabs.

Could you explain more of what you mean for 3.?

**Comment by willlarche** [comment]
All the TODOs have been vetted and are updated. 

It looks like our way of writing the TODOs is the best way for us as we have 4 code labs in our course (unlike StartupName) so we wont' be changing anything else.

All completed code is in the GitHub repo in branches so we'll leave it as is until we get more feedback.

Thank you!!
