### ISSUE TITLE
[104] Small possible typo in step 6

### ISSUE THREAD

**Issue by michdud** [material-components/material-components-flutter-codelabs#155]
In 104 step 6 (Add motion) under "Add reveal motion to the menu button," the tutorial reads "At the top of `backdrop.dart`, outside the scope of any class of function..." when it should probably read "At the top of `backdrop.dart`, outside the scope of any class **or** function...."

**Comment by rami-a** [comment]
Thanks for finding this issue. I've updated the codelab with this change!
