### ISSUE TITLE
[104] Missing todo in step 4 

### ISSUE THREAD

**Issue by michdud** [material-components/material-components-flutter-codelabs#156]
When adding `_BackdropState` to `backdrop.dart`, it seems like there should be a comment about the `ExcludeSemantics` widget in `_buildStack()` above `widget.backLayer`:
````
  // TODO: Add BuildContext and BoxConstraints parameters to _buildStack (104)
  Widget _buildStack() {
    return Stack(
    key: _backdropKey,
      children: <Widget>[
        // (new) TODO: Wrap backLayer in an ExcludeSemantics widget (104)
        widget.backLayer,
        widget.frontLayer,
      ],
    );
  }
````

This todo shows up in step 6 but isn't anywhere else in the tutorial before this that I can see.

**Comment by rami-a** [comment]
Thanks for finding this issue. I've updated the codelab with this change!
