### ISSUE TITLE
[101] Error import in main.dart

### ISSUE THREAD

**Issue by colorain549** [material-components/material-components-flutter-codelabs#157]
`import 'package:Shrine/app.dart';`
The Editor said Target of URL doesn't exist.

When I change the code, as follow,
`import 'package:shrine/app.dart';`
The Editor doesn't find the error below.

**Comment by rami-a** [comment]
Hello, thanks for filing this issue.

I am unable to reproduce this problem. I am using macOS, could you please tell me what OS you are using when you run into this issue?

**Comment by colorain549** [comment]
> Hello, thanks for filing this issue.
> 
> I am unable to reproduce this problem. I am using macOS, could you please tell me what OS you are using when you run into this issue?

Thank you for replying! I have solved out this problem. I am also using macOS10.14.4. I removed the relative code and then imported the correct code, it works and runs successfully!

**Comment by likhit-vivek** [comment]
@colorain549 @rami-a I got the same issue too. It was happening because I opened `material-components-flutter-codelabs` folder instead of `mdc_100_series` inside my editor

**Comment by lisa-liao** [comment]
Hi @colorain549! Does opening the codelab in `mdc_100_series` fix the problem as well?
