### ISSUE TITLE
[101] Could not resolve package for asset packages

### ISSUE THREAD

**Issue by colorain549** [material-components/material-components-flutter-codelabs#158]
Shall we need to download the package from Dart Package ? 
I think we can add this into the tutorial.

**Comment by colorain549** [comment]
> Shall we need to download the package from Dart Package ?
> I think we can add this into the tutorial.

**Comment by colorain549** [comment]
Thank you so much, I can solve this problem!

**Comment by colorain549** [comment]
Thank you so much, I can solve this problem out !

**Comment by colorain549** [comment]
Thank you so much, I have solved this problem out !

**Comment by colorain549** [comment]
Thank you so much, with your help, I can solve it out now!

**Comment by rami-a** [comment]
This is resolved already correct? I'm going to close the issue. Re-open if you're still having trouble
