### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by viveksakpal** [material-components/material-components-flutter-codelabs#160]
https://codelabs.developers.google.com/codelabs/mdc-101-flutter/#3

Add the TextField widgets
Add two new text fields and a spacer after SizedBox(height: 120.0).

in Example 
// spacer
SizedBox(height: 12.0),

**Comment by rami-a** [comment]
Hey thanks for opening this issue. I believe what is meant is to add the textfields and the spacer after the existing 120 height sized box that is already in the code. Hopefully that makes sense!
