### ISSUE TITLE
MDC-103 got error

### ISSUE THREAD

**Issue by squalltua** [material-components/material-components-flutter-codelabs#169]
Compiler message:
path/to/flutter/.pub-cache/hosted/pub.dartlang.org/intl-0.15.8/lib/intl.dart:34:6: Error: Error when reading 'path/to/flutter/.pub-cache/hosted/pub.dartlang.org/intl-0.15.8/lib/src/intl/bidi_utils.dart': No such file or directory
part 'src/intl/bidi_utils.dart';

path/to/flutter/.pub-cache/hosted/pub.dartlang.org/intl-0.15.8/lib/intl.dart:34:6: Error: Can't use 'path/to/flutter/.pub-cache/hosted/pub.dartlang.org/intl-0.15.8/lib/src/intl/bidi_utils.dart' as a part, because it has no 'part of' declaration.
part 'src/intl/bidi_utils.dart';
     ^

what wrong? I just follow the tutorial and try to fix. but I cannot understand about error

**Comment by lisa-liao** [comment]
Hi @squalltua, thanks for opening this issue! What is the output of `flutter doctor`?

**Comment by squalltua** [comment]
@lisa-liao 
[✓] Flutter (Channel stable, v1.5.4-hotfix.2, on Mac OS X 10.14.5 18F132, locale en-TH)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 10.2.1)
[✓] Android Studio (version 3.4)
[!] VS Code (version 1.36.0)
    ✗ Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter
[✓] Connected device (1 available)

! Doctor found issues in 1 category.

**Comment by lisa-liao** [comment]
It looks like you may need to install the Flutter extension from https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter. Please let us know if the error still comes up after you have installed the extension. Thanks!

**Comment by squalltua** [comment]
@lisa-liao 
I'm coding on Android Studio, not the Visual Studio Code.
I try installing the package with `pub get` it result is OK no any error.

I think cause from `intl.dart` package and if cannot find bidi_utils.dart (I don't know what is it)

**Comment by lisa-liao** [comment]
The issue may be similar to [this](https://stackoverflow.com/questions/50416380/not-able-to-import-the-intl-package-for-dart). Please follow the accepted answer, and let us know if the issue still remains. Thanks!

**Comment by squalltua** [comment]
Not work.
I follow them step. I got an error about this

``````
flutter/.pub-cache/hosted/pub.dartlang.org/intl-0.15.8/lib/src/intl/bidi_formatter.dart:68:28: Error: The getter 'TextDirection' isn't defined for the class 'BidiFormatter'.
 - 'BidiFormatter' is from 'package:intl/intl.dart' ('path/to/flutter/.pub-cache/hosted/pub.dartlang.org/intl-0.15.8/lib/intl.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'TextDirection'.
      : contextDirection = TextDirection.LTR,
                           ^^^^^^^^^^^^^
```````

**Comment by willlarche** [comment]
@squalltua , have you rebooted your machine since the problem occurred? (I know it's a non-engineering suggestion but it works for far too many engineering problems!)

**Comment by squalltua** [comment]
@willlarche yes

**Comment by lisa-liao** [comment]
@squalltua Can you try deleting all downloaded pub packages and re-installing with `flutter packages get`? Also make sure that the `pubspec.yaml` file in your app folder
is the same as https://github.com/material-components/material-components-flutter-codelabs/blob/104-complete/mdc_100_series/pubspec.yaml. Thanks!
