### ISSUE TITLE
CodeLab has wrong git branch listed

### ISSUE THREAD

**Issue by ianegordon** [material-components/material-components-flutter-codelabs#17]
@skabber originally posted this to the ios-odelabs repo:

https://codelabs.developers.google.com/codelabs/mdc-103-flutter/index.html
The MDC-103 Flutter codelab states that the branch to us is this.

git clone https://github.com/material-components/material-components-flutter-codelabs.git
cd material-components-flutter-codelabs
git checkout 102-starter_and_101-complete
The correct branch is 103-starter_and_102-complete

**Comment by willlarche** [comment]
Thank you! Corrected.
