### ISSUE TITLE
Typo in mdc-101 step 4

### ISSUE THREAD

**Issue by flashcaps00** [material-components/material-components-flutter-codelabs#170]
Error in the "Add the TextField widgets" section of mdc-101 step 4.

"Add two new text fields and a spacer after SizedBox(height: 120.0)." should read as "Add two new text fields and a spacer after SizedBox(height: 12.0)." based on what is in the code and rest of the directions.

Image below:
<img width="780" alt="Screen Shot 2019-07-13 at 11 45 24 PM" src="https://user-images.githubusercontent.com/31498155/61179063-deb5a800-a5c8-11e9-9143-0f9ada7b09da.png">

**Comment by lisa-liao** [comment]
Hi @flashcaps00, thanks for raising this issue! I believe the `SizedBox(height: 120.0)` in the instructions is referring to the reference to it in login.dart (not from this code snippet). Please let us know if you have any other questions!
