### ISSUE TITLE
Flat button not respecting buttonTheme when used as ButtonBar child component.

### ISSUE THREAD

**Issue by maxwillf** [material-components/material-components-flutter-codelabs#171]
I'm not sure if this is due to flutter version conflict or anything (i'm using the supposedly stable version 1.12.13+hotfix.5) but when i was in the middle of MDC-103 i realized that the shrine app "Next" Raised Button did change correctly when the buttonTheme attribute was changed, but for some reason the "Cancel" Flat Button didn't.
Just like the image below shows, the flat button remains the same, as opposed to the brown font showed in the codelab. 

![image](https://user-images.githubusercontent.com/26348725/70839881-ce129380-1ded-11ea-97db-9a482d72d5c8.png)

I found that adding  ButtonTextTheme.normal to buttonTextTheme in buttonBarTheme fixes this issue but since there is no sign of this configuration in the 104-complete branch of this codelab, i thought i should create this issue as it might be a bug.

**Comment by perclasson** [comment]
This has now been fixed and updated.
