### ISSUE TITLE
Renaming

### ISSUE THREAD

**Issue by coreycarter10** [material-components/material-components-flutter-codelabs#187]
Text(
                    product.name,
                    style: theme.textTheme.title,
                    maxLines: 1,
                  ),

The style inside of this text field is outdated. theme.textTheme.title has been renamed to theme.textTheme.headline6

**Comment by clocksmith** [comment]
https://github.com/material-components/material-components-flutter-codelabs/pull/186/files and https://github.com/material-components/material-components-flutter-codelabs/pull/189 are outstanding PRs that solve this issue

**Comment by Renzo-Olivares** [comment]
Fixed by #189
