### ISSUE TITLE
MDC-101 Flutter: Material Components (MDC) Basics (Flutter) minor issue

### ISSUE THREAD

**Issue by dev-aentgs** [material-components/material-components-flutter-codelabs#188]
In [MDC-101 Flutter: Material Components (MDC) Basics (Flutter) - step 4](https://codelabs.developers.google.com/codelabs/mdc-101-flutter/#3), at the end it is given:

> You should now see a page with two text fields for Username and Password! Check out the floating label and ink ripple animations:

The ink ripple animations are not visible at this stage.

**Comment by Renzo-Olivares** [comment]
Instructions updated.
