### ISSUE TITLE
103 - PrimaryColorOverride

### ISSUE THREAD

**Issue by Prathik-Jain** [material-components/material-components-flutter-codelabs#19]
I get the follwing error 
> [dart] The method 'PrimaryColorOverride' isn't defined for the class '_LoginPageState'.

when I try to use : 
```dart
PrimaryColorOverride(
  color: kShrineAltYellow, // Changed code
  child: TextField(
    controller: _usernameController,
    decoration: InputDecoration(
      labelText: 'Username',
    ),
  ),
),
```

**Also** `colors.dart` needs to be imported in `login.dart` to run the code above and 
```dart
Image.asset(
  'assets/diamond.png',
  color: kShrineBackgroundWhite, 
),
```
Mentioning that would help!

**Comment by willlarche** [comment]
Hi!! I took a look at that lab and I wonder if maybe you missed a step 
### Modify typography and label styles 

In it is the snippet about importing `colors.dart` in `login.dart` and the adding of the `PrimaryColorOverride` class.

![screen shot 2018-05-11 at 4 27 58 pm](https://user-images.githubusercontent.com/1271525/39950761-951c16a2-5538-11e8-8521-1138d4e972db.png)

**Comment by Prathik-Jain** [comment]
You're right! I missed it! Thanks!
