### ISSUE TITLE
Outdated content in MDC-103 Step #5

### ISSUE THREAD

**Issue by paxcodes** [material-components/material-components-flutter-codelabs#196]
In [the 5th page](https://codelabs.developers.google.com/codelabs/mdc-103-flutter/#4), it talks about overriding the accentColor when the theme's accentColor is already set to kShrineBrown900.

It also says,

> Type into a text field—decorations and floating placeholder renders in the correct **Accent color.**

When the screenshot shows that it's rendering the **primaryColor**.

**Comment by Renzo-Olivares** [comment]
Fixed by #198 , 103 codelab instructions updated
