### ISSUE TITLE
Blank Screen When Running the App

### ISSUE THREAD

**Issue by krisnaw** [material-components/material-components-flutter-codelabs#20]
Hi, I'm really new to Flutter & Dart
I'm facing blank screen on iOS Simulator and stuck on installing APK on Android.

1. git clone https://github.com/material-components/material-components-flutter-codelabs.git
2. cd material-components-flutter-codelabs
3. git checkout 101-starter
4. flutter create mdc_100_series
5. Open Android Studio.
6. Delete the testing files widget_test.dart
7. No prompt, since I already install flutter package on my IntelliJ
8. Run app on iOS simulator resulting blank white screen, with this error

`[VERBOSE-2:dart_error.cc(16)] Unhandled exception:
NoSuchMethodError: Attempted to use type 'ShrineApp' as a function. Since types do not define a method 'call', this is not possible. Did you intend to call the ShrineApp constructor and forget the 'new' operator?
Receiver: ShrineApp
Tried calling: ShrineApp()
#0      Object.noSuchMethod (dart:core-patch/dart:core/object_patch.dart:46)
#1      main (/Users/krisna/Work/flutter/material-components-flutter-codelabs/mdc_100_series/lib/main.dart:19:32)
#2      _startIsolate.<anonymous closure> (dart:isolate-patch/dart:isolate/isolate_patch.dart:279)
#3      _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:165)
`

**Comment by willlarche** [comment]
Hi, Krisna! That sounds like an error relating to Dart 2. You seem to still have an older version of Flutter and Dart that doesn't accept the new Dart 2 syntax. In Dart 2, you don't have to include `new` in all your calls to the constructor.

Try a couple things. 

First, try going to IntelliJ IDEA menu and clicking on Check for Updates. There is probably an update for IntelliJ and updates for the Dart and Flutter plugins.

If this is all up to date and you still have a problem, go to IntelliJ IDEA -> Preferences -> Languages & Frameworks -> Flutter and make sure "Run applications in Dart 2.0 mode" is set to "Enable Dart 2"

Write back if you still have problems.

**Comment by krisnaw** [comment]
Hi @willlarche 
Thanks for the response. 

I've made it work on both iOS and Android simulator after updating the IntelliJ IDEA & enabling Dart 2. 
But when I tried to run on a real device (Android 8.0.0 | using USB-C to USB-C 3.1), it keeps on the 
`Installing build/app/outputs/apk/app.apk` process.

**Comment by Sfshaza** [comment]
@krisnaw, did you set your Android device to developer mode?

**Comment by krisnaw** [comment]
Hi @Sfshaza 
Yes, I've set my device to developer mode.

1. I tried making a simple app using `flutter create test-app` first and run it on my device. It works fine.
2. After that, I'm cloning the material design app and following the steps. Then it stuck on the `Installing build/app/outputs/apk/app.apk` process.

**Comment by Sfshaza** [comment]
In the first report, you say you're seeing error messages about "new"? Is that what's happening when you use the MDC code on your device? If that's the case, it sounds like a versioning issue.

**Comment by krisnaw** [comment]
Hi @Sfshaza 

The first issue is caused by outdated Flutter & Dart on my IntelliJ. And already fixed by following @willlarche suggestion. So it works fine when I run it on both iOS and Android simulltor, but stuck on `Installing build/app/outputs/apk/app.apk` when I tried to run on real device.

**Comment by krisnaw** [comment]
Updates
This is the error I getting after enable verbose mode when running the app on device
```
           
           Error type 3
           Error: Activity class {com.example.mdc100series/com.example.mdc100series.MainActivity} does not exist.
[        ] Waiting for observatory port to be available...
```

**Comment by willlarche** [comment]
I spoke with someone who knew about this stuff. 

Docs on the Android manifest are at:
https://developer.android.com/guide/topics/manifest/manifest-intro

The error mentions the component name
"com.example.mdc100series/com.example.mdc100series.MainActivity".  The
part of the component name before the slash is the application package
name, and after the slash is the activity class.  Some checks to do:
  * Does the manifest specify the package name "com.example.mdc100series"?
  * Does the package include an activity named ".MainActivity"?
  * Does the Java code in the APK include an activity class named
"com.example.mdc100series.MainActivity"?

**Comment by krisnaw** [comment]
Hi @willlarche 
Thanks for the responses

1. Does the manifest specify the package name? Yes
`<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.example.mdc100series">`

2. Does the package include an activity name ".MainActivity"? Yes, there is a file named MainActivity

3. How do I check if the APK ?

**Comment by willlarche** [comment]
Hmm. I'm not expert enough in Android to answer that. I'd ask for more help in the Flutter chat room: https://gitter.im/flutter/flutter

**Comment by willlarche** [comment]
Going to close since it's an issue on using IDE. If you learn anything that's really useful for us to add to the setup instructions, report back.
