### ISSUE TITLE
Coding error

### ISSUE THREAD

**Issue by SankThomas** [material-components/material-components-flutter-codelabs#205]
In the last part of MDC-103, the _passwordController for the password TextField is accidentally named _usernameController

Code snippet below

TextField(
  controller: _usernameController,
  decoration: InputDecoration(
    labelText: 'Password',
    labelStyle: TextStyle(
        color: _passwordFocusNode.hasFocus
           ? Theme.of(context).accentColor
           : _unfocusedColor),
  ),
  focusNode: _passwordFocusNode

**Comment by Renzo-Olivares** [comment]
Duplicate issue #203
