### ISSUE TITLE
This commands r not working

### ISSUE THREAD

**Issue by debajyatibanerjee0002** [material-components/material-components-flutter-codelabs#208]
C:\Users\user>flutter doctor -v
Checking Dart SDK version...
Building flutter tool...
Running pub upgrade...
flutter/packages/flutter_tools/lib/src/project.dart:526:1: Error: The '===' operator is not supported.
=======
^
flutter/packages/flutter_tools/lib/src/project.dart:526:4: Error: The '===' operator is not supported.
=======
   ^
flutter/packages/flutter_tools/lib/src/project.dart:344:78: Error: Can't find '}' to match '{'.
class IosProject extends FlutterProjectPlatform implements XcodeBasedProject {
                                                                             ^
flutter/packages/flutter_tools/lib/src/project.dart:682:1: Error: Classes can't be declared inside other classes.
Try moving the class to the top-level.
class AndroidProject extends FlutterProjectPlatform {
^^^^^
flutter/packages/flutter_tools/lib/src/project.dart:682:22: Error: Expected a class member, but got 'extends'.
class AndroidProject extends FlutterProjectPlatform {
                     ^^^^^^^
flutter/packages/flutter_tools/lib/src/project.dart:682:30: Error: A method declaration needs an explicit list of parameters.
Try adding a parameter list to the method declaration.
class AndroidProject extends FlutterProjectPlatform {
                             ^^^^^^^^^^^^^^^^^^^^^^
flutter/packages/flutter_tools/lib/src/project.dart:850:1: Error: Enums can't be declared inside classes.
Try moving the enum to the top-level.
enum AndroidEmbeddingVersion {
^^^^
flutter/packages/flutter_tools/lib/src/project.dart:858:1: Error: Classes can't be declared inside other classes.
Try moving the class to the top-level.
class WebProject extends FlutterProjectPlatform {
^^^^^
flutter/packages/flutter_tools/lib/src/project.dart:858:18: Error: Expected a class member, but got 'extends'.
class WebProject extends FlutterProjectPlatform {
                 ^^^^^^^
flutter/packages/flutter_tools/lib/src/project.dart:858:26: Error: A method declaration needs an explicit list of parameters.
Try adding a parameter list to the method declaration.
class WebProject extends FlutterProjectPlatform {
                         ^^^^^^^^^^^^^^^^^^^^^^
Error: Unable to create dart snapshot for flutter tool.
^CTerminate batch job (Y/N)? y

C:\Users\user>

**Comment by guidezpl** [comment]
This should be fixed, please upgrade (flutter upgrade) and reopen if you're still facing this issue
