### ISSUE TITLE
Vertical View and Horizontal View

### ISSUE THREAD

**Issue by sutiknosofjan** [material-components/material-components-flutter-codelabs#209]
if change layout to Asymmetric View any problem :
1. Text Title change to <Name>... (if long name)
2. Vertical View : its Ok, but if Horizontal View : image will be scratch to small size
2a. how to change to Normal View (not use Asymmetric) ?

**Comment by guidezpl** [comment]
Hi, sorry we missed this. This question is more appropriate for forums such as the [Discord](https://discord.gg/N7Yshp4) or StackOverflow
