### ISSUE TITLE
[MDC-101] Step 5 - Typo in 'Choosing between text and c****ontained buttons'

### ISSUE THREAD

**Issue by marcin-wicha** [material-components/material-components-flutter-codelabs#214]
Current:
![image](https://user-images.githubusercontent.com/23581770/97881442-b2282100-1d22-11eb-9620-5915d2c3c352.png)

Expected:
'Choosing between text and contained buttons'

**Comment by guidezpl** [comment]
Thanks for reporting, this has been been fixed
