### ISSUE TITLE
MDC-102 Flutter #6 Make a card collection deprecation warnings

### ISSUE THREAD

**Issue by Roolingen** [material-components/material-components-flutter-codelabs#216]
Deprecation warnings:
- Product name text widget's style: (in tutorial) `theme.textTheme.title` -> (I think should be) `theme.textTheme.headline6`
- Product price text widget's style: (in tutorial) `theme.textTheme.body2` -> (I think should be) `theme.textTheme.bodyText1`

I see it is fixed in the code (for the name, price it is changed to subtitle). But the tutorial still needs fixing.

**Comment by guidezpl** [comment]
Thanks for filing, this has been fixed
