### ISSUE TITLE
compileSdkVersion is not specified error

### ISSUE THREAD

**Issue by mcativa** [material-components/material-components-flutter-codelabs#223]
While building the project in 101 the following error appears...

FAILURE: Build failed with an exception.

* Where:
Build file '/Users/mcativa/Documents/GitHub/Material Design/material-components-flutter-codelabs/mdc_100_series/android/build.gradle' line: 26

* What went wrong:
A problem occurred evaluating root project 'android'.
> A problem occurred configuring project ':app'.
   > compileSdkVersion is not specified.

-
While the problems ir reported in ./android/build.gradle' it should be fixed in ./android/app/build.gradle next to:
```
targetSdkVersion 28
//Add following
compileSdkVersion 28
```

**Comment by guidezpl** [comment]
https://github.com/material-components/material-components-flutter-codelabs/pull/240
