### ISSUE TITLE
Deprecated/obsolete parameters/codes in codelab [MDC-103]

### ISSUE THREAD

**Issue by sphinxlikee** [material-components/material-components-flutter-codelabs#224]
I have faced parameters which are deprecated.

step 4
" **textSelectionColor**: kShrinePink100 "

step 5
" **headline**: base.**headline**.copyWith( ... "
" **title**: base.**title**.copyWith( ... "
" This takes a TextTheme and changes how the **headlines**, **titles**, and captions look. "
" Applying the fontFamily in this way applies the changes only to the typography scale values specified in copyWith() (**headline**, **title**, caption). "

step 6
RaisedButton

step 7
FlatButton
RaisedButton

step 9
ElevatedButton's(for raisedbutton) color and TextButton's (for flatbutton) color should update in the widget(login.dart) or in theme data(app.dart).
They don't accept color parameter via buttonTheme, they need elevatedButtonTheme and textButtonTheme.

Could you update them?

P.S.: I'm new on github issues, please don't judge me :)

**Comment by guidezpl** [comment]
Thanks for filing! Fixed
