### ISSUE TITLE
"Using a plugin with Flutter web app" page issue - FlatButton is Deprecated

### ISSUE THREAD

**Issue by purpshell** [material-components/material-components-flutter-codelabs#225]
Step 7 of "Using a plugin with Flutter web app" uses a FlatButton for a link to the privacy policy.. My IDE states that it is deprecated, by flutter.dev/go/material-button-migration-guide

**Comment by guidezpl** [comment]
Indeed, https://codelabs.developers.google.com/codelabs/web-url-launcher#6. Moved to https://github.com/flutter/website/issues/5801
