### ISSUE TITLE
Environment is missing from the pubspec.yaml file

### ISSUE THREAD

**Issue by davidtoltesy** [material-components/material-components-flutter-codelabs#226]
With the latest version of Flutter, you won't be able to run this project because it is outdated. It will stop with an error message. (During the 30 Days of Flutter event, probably a lot of people tried to complete the Codespace tutorial, so this should be fixed. Thanks!)

To solve this problem, add this to the pubspec.yaml file:

`environment:
  sdk: '>=2.10.0 <3.0.0'`

**Comment by guidezpl** [comment]
Thanks for reporting! Fixed
