### ISSUE TITLE
lesson 101 is out-of-date the latest flutter version reports its flutter version is depricated

### ISSUE THREAD

**Issue by ghost** [material-components/material-components-flutter-codelabs#229]
I installed the latest flutter instance (2.0) When I tried to run the application in the codelab I received an message that would be installed with a backward compatible environment.

I don't know how long it will continue to run under the new version. 
I do not think it is a good example for new users of flutter to experience such 
situations for a product that is suppose to be in a production status.

**Comment by guidezpl** [comment]
Thanks for filing, this has been fixed and the updates published soon
