### ISSUE TITLE
Flutter 2.0 changes for Buttons

### ISSUE THREAD

**Issue by viveeeeeek** [material-components/material-components-flutter-codelabs#230]
As of Flutter 2.0 release FlatButton and RaisedButton has been changed to TextButton, ElevatedButton, and OutlinedButton. Still this codelab uses FlatBUtton & RaisedButton. 

Thank You.
![Flutter 2 0 Button Changes](https://user-images.githubusercontent.com/64553247/115439970-d0300200-a22c-11eb-94c5-42fee945bece.png)

**Comment by Katekko** [comment]
I was reading this now

**Comment by guidezpl** [comment]
Thanks for filing, this has been fixed and the updates published soon
