### ISSUE TITLE
MDC-103 Flutter - Step 6 - Incorrect code snippet for changing button elevation

### ISSUE THREAD

**Issue by ruanswanepoel** [material-components/material-components-flutter-codelabs#247]
#### Change the elevation of the NEXT button
This section is intended to change the elevation of the ElevatedButton, however, the current code snippet changes the button's shape (which shouldn't be dowe until step 7).

The snippet should be:
```
// TODO: Add an elevation to NEXT (103)
ElevatedButton(
  child: Text('NEXT'),
  // New code
  style: ButtonStyle(
    elevation: MaterialStateProperty.all(8.0),
  ),
),
```

**Comment by guidezpl** [comment]
Indeed, thanks for filing, will be fixed shortly
