### ISSUE TITLE
Replace `ButtonBar`

### ISSUE THREAD

**Issue by guidezpl** [material-components/material-components-flutter-codelabs#248]
Replace usages of `ButtonBar` with `OverflowBar` in code and go/mdc-101-flutter (and 3 following codelabs) when https://github.com/flutter/flutter/commit/9e082f6ce9c8ed17cad783104adb15edef513021 makes it to a stable release

cc @HansMuller

**Comment by HansMuller** [comment]
Sound good. Are you planning to make the changes?

**Comment by guidezpl** [comment]
I'm under higher workload in the upcoming months, so just wanted to create the issue for tracking

**Comment by HansMuller** [comment]
No problem;  I should be able to make the changes.

**Comment by guidezpl** [comment]
Fixed, will be published shortly.
