### ISSUE TITLE
Typo in MDC-103 step 8

### ISSUE THREAD

**Issue by rignaneseleo** [material-components/material-components-flutter-codelabs#25]
In the [MDC-103 step 8](https://codelabs.developers.google.com/codelabs/mdc-103-flutter/#7) with `brightness: Brightness.light` you changed the status bar from black to pink, but it's written:
> Now the products scroll horizontally in a woven-inspired pattern. Also, the status bar (time and network at the top) is now _**black**_. That's because we changed the AppBar's brightness to light, brightness: Brightness.light

It should be:
> Now the products scroll horizontally in a woven-inspired pattern. Also, the status bar (time and network at the top) is now _**pink**_. That's because we changed the AppBar's brightness to light, brightness: Brightness.light

**Comment by willlarche** [comment]
Oh thanks for catching that. I actually meant that the _text_ is black. So, I've updated it to say that. Let us know if you see anything else!
