### ISSUE TITLE
MDC-104 backdrop.dat - Cannot assign Animation<double> to Listenable

### ISSUE THREAD

**Issue by d029940** [material-components/material-components-flutter-codelabs#256]
In class _BackdropTitle, in the constructor, the type Listenable for the parameter listenable won't work, because it is initialized with _listenable, which is of type Animation<double>. That's simply not possible.

On 
https://codelabs.developers.google.com/codelabs/mdc-104-flutter?continue=https%3A%2F%2Fdevelopers.google.com%2Flearn%2Fpathways%2Fmdc-flutter%3Fhl%3Den%23codelab-%2Fcodelabs%2Fmdc-104-flutter&hl=en#7

code snippet should be updated.

`  const _BackdropTitle({
    Key? key,
    required Listenable listenable,               <--------------
    required this.onPress,
    required this.frontTitle,
    required this.backTitle,
  }) : _listenable = listenable, 
       super(key: key, listenable: listenable);

  final Animation<double> _listenable;`

**Comment by guidezpl** [comment]
Thanks for filing, this will be fixed shortly
