### ISSUE TITLE
kShrinePurple is not defined

### ISSUE THREAD

**Issue by obumnwabude** [material-components/material-components-flutter-codelabs#257]
When [Trying another theme at the 9th step of the MDC 103 Flutter codelab](https://codelabs.developers.google.com/codelabs/mdc-103-flutter#8), VS Code reports the following error
> Undefined name 'kShrinePurple'. Try correcting the name to one that is defined, or defining the name

However, when I append `const kShrinePurple = Color(0xFF5D1094);` to the `colors.dart` file, the error disappears and the new theme reflects. 

But then the instruction to add/set the purple primary color is not in this 9th step of the codelab. Please add the instruction to help others that will be subsequently be taking the codelab.

**Comment by Griizz** [comment]
Can confirm this issue.

**Comment by halilakcan** [comment]
And also kShrineBlack isn't defined in colors.dart file too.

In colors.dart, add the following line;
const kShrineBlack = Colors.black;

**Comment by guidezpl** [comment]
Thanks for flagging, this will be fixed shortly
