### ISSUE TITLE
App Theme does not carry over to home screen (MDC-103 Flutter, Page 4)

### ISSUE THREAD

**Issue by Classiks** [material-components/material-components-flutter-codelabs#258]
Step: MDC-103 Flutter, Page 4

For me, when setting the theme parameter in the MaterialApp Widget, the theme on the login screen changes, but as soon as I tab the "Next" Button, the Home Screen appears with the default theme (e.g. blue app bar).
I downloaded the 104-starter_and_103-complete Version from GitHub and ran it on the devices, but the problem remains, so I don't know if it can be my fault (happy to be corrected).

Debugging on a Pixel 4 Emulation (Android 11) and my Z Fold 2 smartphone (Android 11)

Thanks :)

**Comment by piedaterre** [comment]
Same problem. Have you found any answer?

**Comment by Classiks** [comment]
Sadly not, sorry. But I stopped trying pretty quickly. So not sure whether there is a solution out there by now.

**Comment by guidezpl** [comment]
This has been fixed and will be released shortly
