### ISSUE TITLE
Can not assign TextEditingController to TextField

### ISSUE THREAD

**Issue by vonthomasyang** [material-components/material-components-flutter-codelabs#259]
In step add  TextEditingController to TextField controller: _usernameController got a error as "invalid constant value" as below.
![image](https://user-images.githubusercontent.com/91353749/134930245-e1a00151-d6e5-4983-852e-18d433bcfc48.png)

What we should do for this?

**Comment by guidezpl** [comment]
Sorry for the late reply, the issue here is that your `TextField` is marked const, implying everything below it in the widget tree must also be const.
