### ISSUE TITLE
issue found in Download the codelab start app

### ISSUE THREAD

**Issue by earnestsaunders** [material-components/material-components-flutter-codelabs#26]
https://codelabs.developers.google.com/codelabs/from-java-to-dart/index.html?index=..%2F..%2Findex#6

3. Download the codelab starter app

I downloaded the app files by clicking the green "Download Starter App" button.  In step 4 of this page, it says to delete the testing file (.../test/widget_test.dart).  I found no such file in the directory "material-components-flutter-codelabs/mdc_100_series".

**Comment by willlarche** [comment]
Hey! That link is for the java to dart lab. Which of the MDC codelabs were you doing?

The file will appear after you run `flutter create mdc_100_series`

**Comment by earnestsaunders** [comment]
Hi Will,

I'm trying out the codelab:  MDC-101 Flutter: Mat'l Components (MDC) Basics
(Flutter).

The step 4 about deleting the testing file is in the main step 3 (Download
the codelab starter app).

Thanks!
Rachel

**Comment by willlarche** [comment]
Ok, great. Same thing. The file will appear after you run `flutter create mdc_100_series` which is step 2 in Create the project sub-step above.

If you don't see that file, that's also fine. Deleting it is only necessary if it's there.
