### ISSUE TITLE
brightness in AppBar is deprecated

### ISSUE THREAD

**Issue by RoarGronmo** [material-components/material-components-flutter-codelabs#262]
See picture

![image](https://user-images.githubusercontent.com/11217296/137616930-7f06c187-4557-41ba-ae9e-98b57ecdf867.png)

**Comment by RoarGronmo** [comment]
Please replace with `systemOverlayStyle` like this (see picture)

![image](https://user-images.githubusercontent.com/11217296/137617220-c637d309-de21-4609-9ba5-0bf2cfca31d6.png)

**Comment by guidezpl** [comment]
Thanks for flagging, this will be fixed shortly
