### ISSUE TITLE
When using initialRoute, don’t define a home property.

### ISSUE THREAD

**Issue by asavchuk** [material-components/material-components-flutter-codelabs#264]
In the codelab the MaterialApp uses both home and initialRoute properties.

```
return MaterialApp(
      home: const HomePage(),
      initialRoute: '/login',
      onGenerateRoute: _getRoute,
);
```

How does it relates to the cookbook's warning: When using initialRoute, don’t define a home property.
https://flutter.dev/docs/cookbook/navigation/named-routes

**Comment by guidezpl** [comment]
Thanks for filing, this has been fixed and will be published shortly
