### ISSUE TITLE
In MDC-103 the button 'cancel' is pink instead of brown (while in the image it's brown)

### ISSUE THREAD

**Issue by AndreaPra** [material-components/material-components-flutter-codelabs#266]
# Codelab: MDC-103
## Step: 4

I set all the theme's color as said in the codelab, but i noticed the pink color of the _text_ of the button 'cancel' in the login frame. I was wondering if I missed something or, maybe, it's because the button 'cancel' is different from the button 'next' and so a different theme color is applied by default.

**Comment by guidezpl** [comment]
This has been fixed and will be fixed shortly, thanks for reporting.
