### ISSUE TITLE
MDC-103 Flutter problems

### ISSUE THREAD

**Issue by ghost** [material-components/material-components-flutter-codelabs#269]
[8. Change the layout](https://codelabs.developers.google.com/codelabs/mdc-103-flutter#7)
Replace GridView with AsymmetricView
In home.dart, change the whole file to the following:

result:
"message": "Undefined name 'SystemUiOverlayStyle'.\nTry correcting the name to one that is defined, or defining the name.",

add _import 'package:flutter/services.dart';_ to the code, please.

**Comment by guidezpl** [comment]
Thanks for flagging, this will be fixed shortly!
