### ISSUE TITLE
The meta package is no longer needed to import to mark the properties as required

### ISSUE THREAD

**Issue by hzmalix** [material-components/material-components-flutter-codelabs#270]
Step 4 of the Codelab "[MDC-104 Flutter: Material Advanced Components (Flutter)](https://codelabs.developers.google.com/codelabs/mdc-104-flutter)" states that The meta-package is imported in order to mark the properties @required. 
It's no longer required in the latest Flutter versions.

**Comment by guidezpl** [comment]
Thanks for flagging, this will be fixed later today
