### ISSUE TITLE
Invalid Flutter Documentation links

### ISSUE THREAD

**Issue by FabianUntermoser** [material-components/material-components-flutter-codelabs#272]
There are some links to the Flutter documentation, which do not work.
Examples:
- https://docs.flutter.io/flutter/material/Icons-class.html
- https://docs.flutter.io/flutter/widgets/Icon-class.html

They should be replaced with the correct links:
- https://api.flutter.dev/flutter/material/Icons-class.html
- https://api.flutter.dev/flutter/widgets/Icon-class.html

**Comment by guidezpl** [comment]
Hi, can you please link the pages with the invalid links?

**Comment by guidezpl** [comment]
Found them, fixed soon.
