### ISSUE TITLE
Android SDK and Kotlin versions not compatible with fresh install of Flutter

### ISSUE THREAD

**Issue by raladdin** [material-components/material-components-flutter-codelabs#273]
I had to change the compileSdkVersion and targetSdkVersion to 31 in android/app/build.gradle, add android:exported="true" to android/app/AndroidManifest.xml and set ext.kotlin_version = '1.6.20' in android/build.gradle to get the MDC-101 to compile on a fresh install.

**Comment by guidezpl** [comment]
Hi, I believe I fixed these issues (https://github.com/material-components/material-components-flutter-codelabs/commit/95019607d1f959c8c71316e4c3433baec3fe48cb) just before you ran into them, could you pull the branch and confirm if it compiles without any further modifications?

**Comment by raladdin** [comment]
I confirm the issues are fixed by that commit! Thank you, closing the issue.
