### ISSUE TITLE
The  vertical space for cards is a margin not a padding as it is referenced in the codelab MDC-102 Flutter: Material Structure and Layout 

### ISSUE THREAD

**Issue by jeisux92** [material-components/material-components-flutter-codelabs#276]
The  vertical space for cards is a margin not a padding as it is referenced in the page 

![image](https://user-images.githubusercontent.com/31553757/173696533-b0af49fa-1703-4450-9fba-276abe5581ec.png)

We could see the padding field is not a valid one

![image](https://user-images.githubusercontent.com/31553757/173696972-f3ae3c8b-b51f-43ac-a0c1-e5e90f83b5db.png)

The  4 points (logical pixels) mentioned belongs to the margin

![image](https://user-images.githubusercontent.com/31553757/173697613-54f8ba23-f836-4aac-b6a9-154ffbe69d19.png)

**Comment by guidezpl** [comment]
Thanks for reporting, this will be fixed upon the next publishing of the codelabs.
