### ISSUE TITLE
There's no constant named 'labelLarge' in 'TextOverflow'.

### ISSUE THREAD

**Issue by GolakiyaVishal** [material-components/material-components-flutter-codelabs#286]
This is link for  [code lab](https://codelabs.developers.google.com/codelabs/mdc-103-flutter#4)

in section 5 Modify Typography and label style.

`// TODO: Change innermost Column (103)
children: <Widget>[
// TODO: Handle overflowing labels (103)
  Text(
    product.name,
    style: theme.textTheme.button,
    softWrap: false,
    overflow: TextOverflow.labelLarge,
    maxLines: 1,
  ),
  const SizedBox(height: 4.0),
  Text(
    formatter.format(product.price),
    style: theme.textTheme.bodySmall,
  ),
  // End new code
],`

in this sample code required to change overflow property.
`overflow: TextOverflow.labelLarge`
to
`overflow: TextOverflow.ellipsis`

**Comment by guidezpl** [comment]
Thanks for filing an issue, this will be fixed shortly.
