### ISSUE TITLE
headline5

### ISSUE THREAD

**Issue by Apliarte** [material-components/material-components-flutter-codelabs#288]
parece que  headline5 ya esta obsoleto y se usa en el codelabs

**Comment by guidezpl** [comment]
Hi, can you please share a link where you are seeing `headline5`?

**Comment by Apliarte** [comment]
![image](https://github.com/material-components/material-components-flutter-codelabs/assets/114274314/29799d5e-b2a7-41a5-9d6f-03bba94e6c01)

**Comment by guidezpl** [comment]
I'm not sure where you're seeing this. 

Both the [codelab](https://codelabs.developers.google.com/codelabs/mdc-103-flutter#4) and code have been updated:

<img width="782" alt="image" src="https://github.com/material-components/material-components-flutter-codelabs/assets/6655696/c6034ad9-bf96-4288-9b8b-dcf50f75b44c">


https://github.com/material-components/material-components-flutter-codelabs/blob/104-starter_and_103-complete/mdc_100_series/lib/app.dart#L73-L96

 and 

https://github.com/material-components/material-components-flutter-codelabs/blob/104-complete/mdc_100_series/lib/app.dart#L99-L122

**Comment by guidezpl** [comment]
Without further information, closing
