### ISSUE TITLE
MDC-103 Flutter - step 7 adding features

### ISSUE THREAD

**Issue by prorege** [material-components/material-components-flutter-codelabs#292]
Textbutton and ElevatedButton widgets has missed one  ' ) '

---

ElevatedButton(
  child: const Text('NEXT'),
  onPressed: () {
    Navigator.pop(context);
  },
  style: ElevatedButton.styleFrom(
    elevation: 8.0,
    shape: const BeveledRectangleBorder(
      borderRadius: BorderRadius.all(Radius.circular(7.0)),
    ),
  ),
  
  this is your example, but you missed on ' ( '  
  below is correct.

ElevatedButton(
child: const Text('NEXT'),
onPressed: () {
Navigator.pop(context);
},
style: ElevatedButton.styleFrom(
elevation: 8.0,
shape: const BeveledRectangleBorder(
borderRadius: BorderRadius.all(Radius.circular(7.0)),
),
),
),

**Comment by guidezpl** [comment]
Indeed, thanks for reporting. Fixed
