### ISSUE TITLE
MDC-101 Flutter:Material Components Basics - Add TextField widgets - Wrong height

### ISSUE THREAD

**Issue by arromero4** [material-components/material-components-flutter-codelabs#295]
When you add TextField widgets the height in the instruction is const SizedBox(height: 120.0) but in the example is const SizedBox(height: 12.0),
![image](https://github.com/material-components/material-components-flutter-codelabs/assets/57555202/5ae02719-0154-4ca1-b1b7-06545de44c6b)

**Comment by guidezpl** [comment]
Thanks for reporting, the fix will be out shortly
