### ISSUE TITLE
MDC-104 Flutter:Material Advanced Components - Add a branded icon - Error

### ISSUE THREAD

**Issue by arromero4** [material-components/material-components-flutter-codelabs#296]
When we create a new class _BackdropTitle.
IDE shows an error in this line child: const ImageIcon(AssetImage('assets/slanted_menu.png')),
![image](https://github.com/material-components/material-components-flutter-codelabs/assets/57555202/be295709-df24-4746-a834-04b2a1d81ff3)

it should be  child: const ImageIcon(AssetImage('/slanted_menu.png'))
![image](https://github.com/material-components/material-components-flutter-codelabs/assets/57555202/aac92463-e13c-467b-a275-6d19e5fbb458)

**Comment by guidezpl** [comment]
Can you please share the error? I'm not getting an error with this code in the 104-complete branch

**Comment by arromero4** [comment]
I'll close the issue I finished the codelab I can't see the error again.
