### ISSUE TITLE
MDC-104 add motion: onTap not set up

### ISSUE THREAD

**Issue by keyranova** [material-components/material-components-flutter-codelabs#30]
I had an error due to onTap function with the _FrontLayer setup.

I had to go into the source code to find out how to set up the GestureDetector since it's not mentioned in the tutorial.

**Comment by keyranova** [comment]
welp. looks like it's set up in the next section of the tutorial, but still an issue since the error wouldn't let products load.

**Comment by willlarche** [comment]
Thank you for reporting that!

I think I see the issue you're speaking of. "Add a shape to the front layer" is where `_FrontLayer` is defined. In that step, we haven't added the `onTap` field to the `_FrontLayer` widget. But there was still a call to that field in the `_buildStack()` function.

I've removed any use of `onTap` from that step so it's only mentioned in  "Toggle the front layer".

If that's still not correct, please reopen the ticket!
