### ISSUE TITLE
MDC-104 Parameter onTap not implemented yet on step 6.

### ISSUE THREAD

**Issue by castrors** [material-components/material-components-flutter-codelabs#32]
The onTap parameter will be implemented only on step 7. 

The codelab is mdc-104-flutter

**Copy-pasted from step 6:**
```dart
return Stack(
      key: _backdropKey,
      children: <Widget>[
        widget.backLayer,
        PositionedTransition(
          rect: layerAnimation,
          child: _FrontLayer(
            onTap: _toggleBackdropLayerVisibility,
            child: widget.frontLayer,
          ),
        ),
      ],
    );
```

**Comment by willlarche** [comment]
Hey! Thank you for reporting this. I'm pretty sure it's the same as #30 which we fixed just a few moments ago.

Refresh your browser and see if step 6 is correct now. Reopen this issue if it's still wrong!
