### ISSUE TITLE
MDC-104 Flutter: Material Advanced Components (Flutter) - Step 4

### ISSUE THREAD

**Issue by msphotosite** [material-components/material-components-flutter-codelabs#33]
Widget _buildStack() {
    child: Stack(
    key: _backdropKey,
      children: <Widget>[
        widget.backLayer,
        widget.frontLayer,
      ],
    );
  }

contains an error. 

Replace it with:

  Widget _buildStack() {
    return Stack(
    key: _backdropKey,
      children: <Widget>[
        widget.backLayer,
        widget.frontLayer,
      ],
    );
  }

**Comment by willlarche** [comment]
Thank you! Great catch. I've fixed it there and in the place where we wrap the frontLayer. Let me know if it's not correct still.
