### ISSUE TITLE
BeveledRectangleBorder is not defined

### ISSUE THREAD

**Issue by arjunkn** [material-components/material-components-flutter-codelabs#35]
Showing error on login.dart The method 'BeveledRectangleBorder' isn't defined for the class '_LoginPageState'. is there any thing else to import?

**Comment by willlarche** [comment]
You don't have to do anything but import `material.dart`. But this class is kinda new. Maybe your Flutter is out of date. Try running `flutter upgrade`.

**Comment by arjunkn** [comment]
Thanks @willlarche that was the problem.
