### ISSUE TITLE
MDC-103 Flutter: Material Theming with Color, Shape, Elevation, and Type (Flutter)

### ISSUE THREAD

**Issue by Zheng-Shuo** [material-components/material-components-flutter-codelabs#36]
Hi, i got an exception when i ran the demo code,  i don't know how to fix it, please help me, thank you.

``` Dart
class HomePage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        brightness: Brightness.light,
        leading: IconButton(
          icon: Icon(Icons.menu),
          onPressed: () {
            print('Menu button');
          },
        ),
        title: Text('SHRINE'),
        actions: <Widget>[
          IconButton(
            icon: Icon(Icons.search),
            onPressed: () {
              print('Search button');
            },
          ),
          IconButton(
            icon: Icon(Icons.tune),
            onPressed: () {
              print('Filter button');
            },
          ),
        ],
      ),
      body: AsymmetricView(products: getProducts(Category.all)),
    );
  }
}
```

I/flutter ( 4768): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter ( 4768): The following _CompileTimeError was thrown building HomePage(dirty):
I/flutter ( 4768): 'file:*****/lib/home.dart': error: line 49 pos 38:
I/flutter ( 4768): lib/home.dart:49:38: Error: A value of type 'dart.core::List<#lib1::Product>' can't be assigned to a
I/flutter ( 4768): variable of type 'dart.core::List<#lib2::Product>'.
I/flutter ( 4768): Try changing the type of the left hand side, or casting the right hand side to
I/flutter ( 4768): 'dart.core::List<#lib2::Product>'.
I/flutter ( 4768):       body: AsymmetricView(products: getProducts(Category.all)),
I/flutter ( 4768):                                      ^
I/flutter ( 4768):       body: AsymmetricView(products: getProducts(Category.all)),
I/flutter ( 4768):                                      ^
I/flutter ( 4768): 
I/flutter ( 4768): When the exception was thrown, this was the stack:
I/flutter ( 4768): #0      StatelessElement.build (package:flutter/src/widgets/framework.dart:3695:28)
I/flutter ( 4768): #1      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3642:15)
I/flutter ( 4768): #2      Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter ( 4768): #3      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3622:5)
I/flutter ( 4768): #4      ComponentElement.mount (package:flutter/src/widgets/framework.dart:3617:5)
I/flutter ( 4768): #5      Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
I/flutter ( 4768): #6      Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
I/flutter ( 4768): #7      SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4654:14)
I/flutter ( 4768): #8      Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
I/flutter ( 4768): #9      Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
I/flutter ( 4768): #10     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
I/flutter ( 4768): #11     Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter ( 4768): #12     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3622:5)
I/flutter ( 4768): #13     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3617:5)
I/flutter ( 4768): #14     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
I/flutter ( 4768): #15     Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
I/flutter ( 4768): #16     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4654:14)
I/flutter ( 4768): #17     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
I/flutter ( 4768): #18     Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
I/flutter ( 4768): #19     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4654:14)
I/flutter ( 4768): #20     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
I/flutter ( 4768): #21     Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
I/flutter ( 4768): #22     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4654:14)
I/flutter ( 4768): #23     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
I/flutter ( 4768): #24     Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
I/flutter ( 4768): #25     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4654:14)
I/flutter ( 4768): #26     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
I/flutter ( 4768): #27     Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
I/flutter ( 4768): #28     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
I/flutter ( 4768): #29     Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter ( 4768): #30     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3622:5)
I/flutter ( 4768): #31     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3769:11)
I/flutter ( 4768): #32     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3617:5)
I/flutter ( 4768): #33     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
I/flutter ( 4768): #34     Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
I/flutter ( 4768): #35     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
I/flutter ( 4768): #36     Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter ( 4768): #37     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3622:5)
I/flutter ( 4768): #38     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3617:5)
I/flutter ( 4768): #39     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
I/flutter ( 4768): #40     Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
I/flutter ( 4768): #41     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
I/flutter ( 4768): #42     Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter ( 4768): #43     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3622:5)
I/flutter ( 4768): #44     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3769:11)
I/flutter ( 4768): #45     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3617:5)
I/flutter ( 4768): #46     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
I/flutter ( 4768): #47     Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
I/flutter ( 4768): #48     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4654:14)
I/flutter ( 4768): #49     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
I/flutter ( 4768): #50     Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
I/flutter ( 4768): #51     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
I/flutter ( 4768): #52     Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter ( 4768): #53     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3622:5)
I/flutter ( 4768): #54     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3617:5)
I/flutter ( 4768): #55     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
I/flutter ( 4768): #56     Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
I/flutter ( 4768): #57     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4654:14)
I/flutter ( 4768): #58     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
I/flutter ( 4768): #59     Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
I/flutter ( 4768): #60     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
I/flutter ( 4768): #61     Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter ( 4768): #62     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3622:5)
I/flutter ( 4768): #63     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3769:11)
I/flutter ( 4768): #64     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3617:5)
I/flutter ( 4768): #65     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
I/flutter ( 4768): #66     Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
I/flutter ( 4768): #67     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
I/flutter ( 4768): #68     Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter ( 4768): #69     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3622:5)
I/flutter ( 4768): #70     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3617:5)
I/flutter ( 4768): #71     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
I/flutter ( 4768): #72     Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
I/flutter ( 4768): #73     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4654:14)
I/flutter ( 4768): #74     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
I/flutter ( 4768): #75     Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
I/flutter ( 4768): #76     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
I/flutter ( 4768): #77     Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter ( 4768): #78     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3622:5)
I/flutter ( 4768): #79     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3617:5)
I/flutter ( 4768): #80     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
I/flutter ( 4768): #81     Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
I/flutter ( 4768): #82     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
I/flutter ( 4768): #83     Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter ( 4768): #84     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3622:5)
I/flutter ( 4768): #85     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3769:11)
I/flutter ( 4768): #86     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3617:5)
I/flutter ( 4768): #87     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
I/flutter ( 4768): #88     Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
I/flutter ( 4768): #89     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
I/flutter ( 4768): #90     Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter ( 4768): #91     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3622:5)
I/flutter ( 4768): #92     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3769:11)
I/flutter ( 4768): #93     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3617:5)
I/flutter ( 4768): #94     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
I/flutter ( 4768): #95     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4759:32)
I/flutter ( 4768): #96     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
I/flutter ( 4768): #97     Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
I/flutter ( 4768): #98     _TheatreElement.mount (package:flutter/src/widgets/overlay.dart:493:16)
I/flutter ( 4768): #99     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
I/flutter ( 4768): #100    Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
I/flutter ( 4768): #101    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
I/flutter ( 4768): #102    Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter ( 4768): #103    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3622:5)
I/flutter ( 4768): #104    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3769:11)
I/flutter ( 4768): #105    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3617:5)
I/flutter ( 4768): #106    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
I/flutter ( 4768): #107    Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
I/flutter ( 4768): #108    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
I/flutter ( 4768): #109    Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter ( 4768): #110    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3622:5)
I/flutter ( 4768): #111    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3617:5)
I/flutter ( 4768): #112    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
I/flutter ( 4768): #113    Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
I/flutter ( 4768): #114    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4654:14)
I/flutter ( 4768): #115    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
I/flutter ( 4768): #116    Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
I/flutter ( 4768): #117    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
I/flutter ( 4768): #118    Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter ( 4768): #119    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3622:5)
I/flutter ( 4768): #120    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3769:11)
I/flutter ( 4768): #121    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3617:5)
I/flutter ( 4768): #122    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
I/flutter ( 4768): #123    Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
I/flutter ( 4768): #124    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4654:14)
I/flutter ( 4768): #125    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
I/flutter ( 4768): #126    Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
I/flutter ( 4768): #127    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4654:14)
I/flutter ( 4768): #128    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
I/flutter ( 4768): #129    Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
I/flutter ( 4768): #130    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
I/flutter ( 4768): #131    Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter ( 4768): #132    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3622:5)
I/flutter ( 4768): #133    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3769:11)
I/flutter ( 4768): #134    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3617:5)
I/flutter ( 4768): #135    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
I/flutter ( 4768): #136    Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
I/flutter ( 4768): #137    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
I/flutter ( 4768): #138    Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter ( 4768): #139    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3622:5)
I/flutter ( 4768): #140    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3617:5)
I/flutter ( 4768): #141    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
I/flutter ( 4768): #142    Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
I/flutter ( 4768): #143    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
I/flutter ( 4768): #144    Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter ( 4768): #145    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3622:5)
I/flutter ( 4768): #146    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3617:5)
I/flutter ( 4768): #147    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
I/flutter ( 4768): #148    Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
I/flutter ( 4768): #149    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
I/flutter ( 4768): #150    Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter ( 4768): #151    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3622:5)
I/flutter ( 4768): #152    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3617:5)
I/flutter ( 4768): #153    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
I/flutter ( 4768): #154    Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
I/flutter ( 4768): #155    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
I/flutter ( 4768): #156    Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter ( 4768): #157    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3622:5)
I/flutter ( 4768): #158    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3617:5)
I/flutter ( 4768): #159    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
I/flutter ( 4768): #160    Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
I/flutter ( 4768): #161    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4654:14)
I/flutter ( 4768): #162    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
I/flutter ( 4768): #163    Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
I/flutter ( 4768): #164    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
I/flutter ( 4768): #165    Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter ( 4768): #166    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3622:5)
I/flutter ( 4768): #167    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3769:11)
I/flutter ( 4768): #168    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3617:5)
I/flutter ( 4768): #169    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
I/flutter ( 4768): #170    Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
I/flutter ( 4768): #171    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
I/flutter ( 4768): #172    Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter ( 4768): #173    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3622:5)
I/flutter ( 4768): #174    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3617:5)
I/flutter ( 4768): #175    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
I/flutter ( 4768): #176    Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
I/flutter ( 4768): #177    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
I/flutter ( 4768): #178    Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter ( 4768): #179    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3622:5)
I/flutter ( 4768): #180    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3769:11)
I/flutter ( 4768): #181    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3617:5)
I/flutter ( 4768): #182    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
I/flutter ( 4768): #183    Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
I/flutter ( 4768): #184    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
I/flutter ( 4768): #185    Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter ( 4768): #186    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3622:5)
I/flutter ( 4768): #187    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3617:5)
I/flutter ( 4768): #188    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
I/flutter ( 4768): #189    Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
I/flutter ( 4768): #190    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
I/flutter ( 4768): #191    Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter ( 4768): #192    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3622:5)
I/flutter ( 4768): #193    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3617:5)
I/flutter ( 4768): #194    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
I/flutter ( 4768): #195    Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
I/flutter ( 4768): #196    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
I/flutter ( 4768): #197    Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter ( 4768): #198    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3622:5)
I/flutter ( 4768): #199    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3617:5)
I/flutter ( 4768): #200    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
I/flutter ( 4768): #201    Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
I/flutter ( 4768): #202    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
I/flutter ( 4768): #203    Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter ( 4768): #204    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3622:5)
I/flutter ( 4768): #205    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3769:11)
I/flutter ( 4768): #206    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3617:5)
I/flutter ( 4768): #207    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
I/flutter ( 4768): #208    Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
I/flutter ( 4768): #209    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
I/flutter ( 4768): #210    Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter ( 4768): #211    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3622:5)
I/flutter ( 4768): #212    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3617:5)
I/flutter ( 4768): #213    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
I/flutter ( 4768): #214    Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
I/flutter ( 4768): #215    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
I/flutter ( 4768): #216    Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter ( 4768): #217    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3622:5)
I/flutter ( 4768): #218    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3769:11)
I/flutter ( 4768): #219    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3617:5)
I/flutter ( 4768): #220    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
I/flutter ( 4768): #221    Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
I/flutter ( 4768): #222    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
I/flutter ( 4768): #223    Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter ( 4768): #224    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3622:5)
I/flutter ( 4768): #225    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3617:5)
I/flutter ( 4768): #226    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
I/flutter ( 4768): #227    Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
I/flutter ( 4768): #228    RenderObjectToWidgetElement._rebuild (package:flutter/src/widgets/binding.dart:857:16)
I/flutter ( 4768): #229    RenderObjectToWidgetElement.mount (package:flutter/src/widgets/binding.dart:828:5)
I/flutter ( 4768): #230    RenderObjectToWidgetAdapter.attachToRenderTree.<anonymous closure> (package:flutter/src/widgets/binding.dart:774:17)
I/flutter ( 4768): #231    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2222:19)
I/flutter ( 4768): #232    RenderObjectToWidgetAdapter.attachToRenderTree (package:flutter/src/widgets/binding.dart:773:13)
I/flutter ( 4768): #233    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding&WidgetsBinding.attachRootWidget (package:flutter/src/widgets/binding.dart:662:7)
I/flutter ( 4768): #234    runApp (package:flutter/src/widgets/binding.dart:704:7)
I/flutter ( 4768): #235    main (file:///Users/zheng/Documents/android_project/hi_flutter/lib/main.dart:19:16)
I/flutter ( 4768): #236    _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:279:19)
I/flutter ( 4768): #237    _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:165:12)
I/flutter ( 4768): ══════════════════════════════════════════════════════════

**Comment by willlarche** [comment]
Hi, @Zheng-Shuo , I can't reproduce this. Can you let me know which code you're running? Is it from the 103 starter branch? or did you complete 102 on your own and you're running off that?

**Comment by Zheng-Shuo** [comment]
Hi, @willlarche , thank you for your reply,  I think I probably know where I was wrong,
when i write it like this I‘ll get the error:
``` Dart
import 'package:Shrine/model/data.dart';
import 'package:Shrine/model/product.dart';
```
and when i write it like this, it's working fine:
```Dart 
import 'model/data.dart';
import 'model/product.dart';
```
I don't know why, could you explain it?

**Comment by redbrogdon** [comment]
Dart considers these two imports:

    import 'package:Shrine/model/data.dart';

    import 'model/data.dart';

To be different libraries, even if they ultimately point to the same file. So if you import the `data.dart` file both ways inside a single app, the compiler will think you've imported it twice, and give it two different namespaces with two different sets of classes. That's why you saw an error that said:

    A value of type 'dart.core::List<#lib1::Product>' can't be assigned 
    to a variable of type 'dart.core::List<#lib2::Product>'.

As far as the compiler knew, you were using two different classes called `Product` from two different libraries, and the cast failed.

The easiest way to fix this is just to be consistent about how you import things. I generally use the package prefix for everything, personally.

**Comment by Zheng-Shuo** [comment]
@RedBrogdon @willlarche 
I see. Thank you for your help!
