### ISSUE TITLE
MDC-104 uses slanted-menu.png which isn't in any branch but 104-complete

### ISSUE THREAD

**Issue by firsthour** [material-components/material-components-flutter-codelabs#41]
The "Add a Branded Icon" step of MDC-104 references slanted-menu.png which is not in any branch except the final one. This should probably be included in every branch and the pubspec.yaml be updated across all branches to include this asset.

**Comment by willlarche** [comment]
Good catch! @clocksmith , can you add the file to the `101-starter` branch and then rebase the rest. Then add a step in 104 to add the image to the `pubspec.yaml`? If we do it that way, then we don't have to update the images of `pubspec.yaml` that could be in 101-103.

**Comment by clocksmith** [comment]
Done, but still need to properly rebase
