### ISSUE TITLE
Minor instruction issue in MDC-104: Missing import ?

### ISSUE THREAD

**Issue by gemmakbarlow** [material-components/material-components-flutter-codelabs#62]
In [Step 4](https://codelabs.developers.google.com/codelabs/mdc-104-flutter/#3), 'Add the Background Menu' I had to import both  - 

- `backdrop.dart` (as included in the instructions); and 
- `model/product.dart` 

to get things to compile. 

I had completed MDC-103 and then used my work to continue on to MDC-104; unsure if the previous tutorial should have included it at some point - or if the instructions in MDC-104 need to be updated. 

Thanks folks !

**Comment by michdud** [comment]
Thanks for reporting this! I've added an instruction to import `model/product.dart` in [Step 4](https://codelabs.developers.google.com/codelabs/mdc-104-flutter/#3), and written comments to indicate the new imports with more clarity. Please let me know if you had something else in mind and we can take a look!

**Comment by gemmakbarlow** [comment]
Sounds good to me @michdud  - thanks.
