### ISSUE TITLE
MDC-104 Step 7 - code mismatch with codelab instructions

### ISSUE THREAD

**Issue by thevarunshah** [material-components/material-components-flutter-codelabs#64]
The following two lines which need to be replaced in the _ShrineAppState class are actually in the ShrineApp class in the code. Documentation is correct, code needs to be updated so people don't copy/paste into the wrong class and get confused.

// TODO: Add variable for selected Category (104)
// TODO: Add a callback when a Category is tapped (104)

**Comment by thevarunshah** [comment]
Looked at the starter branch for MDC-104 and the problem can't be fixed in code. The documentation needs to highlight that when you convert ShrineApp to a StatefulWidget, the comments stay in the ShrineApp class but the documentation has them in the _ShrineAppState class. If someone isn't paying attention to the class name while trying the codelabs, they can easily miss this detail.

**Comment by michdud** [comment]
Thanks for reporting this! I've removed the [todos](https://codelabs.developers.google.com/codelabs/mdc-104-flutter/#6) you referenced because they are confusing! If this is not what you were thinking, let me know and we can take another look.
