### ISSUE TITLE
MDC-104 Step 7 Toggle the front layer - codelab instructions missing code

### ISSUE THREAD

**Issue by thevarunshah** [material-components/material-components-flutter-codelabs#65]
In the first TODO under this header where it says to add the on-tap callback, the instructions is missing the following line after the onTap callback is declared:
final Widget child;

Without this line, the code doesn't compile at the end of this step.

**Comment by michdud** [comment]
Thanks for reporting this! I've added `final Widget child;` to the bottom of the [codeblock in question](https://codelabs.developers.google.com/codelabs/mdc-104-flutter/#6) for context, and comments next to the new lines of code added. Let me know if this isn't what you had in mind, and we can take another look!
