### ISSUE TITLE
MDC-101 - Incomplete text at the green notice area in step 5 "Pop" 

### ISSUE THREAD

**Issue by BrutalCoding** [material-components/material-components-flutter-codelabs#70]
Incomplete text quoted:

> Navigator maintains a stack of routes just like UINavigationController on iOS. Pushing a route places it at the top of the stack. Popping the stack removes the most recently added route. In app.dart of our app, calling initialRoute: '/login', adds the login screen to the

While I guess it should be ending with "... , adds the login screen to the stack of routes."

You can find this text under the header "Pop", in the green 'notice' area.

URL: https://codelabs.developers.google.com/codelabs/mdc-101-flutter/#4

**Comment by willlarche** [comment]
Great catch @BrutalCoding ! That text was indeed removed by accident. It's been put back.
