### ISSUE TITLE
MDC-103 AsymmetricView not working

### ISSUE THREAD

**Issue by polmp** [material-components/material-components-flutter-codelabs#82]
I followed the tutorial of MDC-103 to include the AsymmetricView, and I got the following error:

`lib/home.dart:47:38: Error: A value of type 'dart.core::List<#lib1::Product>' can't be assigned to a variable of type 'dart.core::List<#lib2::Product>'.`

There is an error in the tutorial. To solve it, we simply need to change the import of the AsymmetricView to:

`import 'package:Shrine/supplemental/asymmetric_view.dart';`

Now it works flawlessly.

**Comment by michdud** [comment]
Thanks for reporting this! Out of curiosity, if you remove the change you created in `home.dart` and instead change the import in `main.dart` for `app.dart` to `package:Shrine/app.dart`, does that also fix the issue? This seems to be the fix recommended by [dart-lang/sdk#33076](https://github.com/dart-lang/sdk/issues/33076).

**Comment by polmp** [comment]
Yes, if we maintain the original import and change the one of main.dart for 
`import 'package:Shrine/app.dart';`

Seems solved too

**Comment by michdud** [comment]
I've added the import fix in `main.dart` to all codelabs, because it seems to be the recommended solution per the Dart issue above. Thanks again for reporting this, and please let me know if you have any problems with/questions about this fix!
