### ISSUE TITLE
[102] Add color: Colors.white in leading IconButton

### ISSUE THREAD

**Issue by bapspatil** [material-components/material-components-flutter-codelabs#91]
In https://codelabs.developers.google.com/codelabs/mdc-102-flutter/#3, under **Add a leading IconButton**:
```
return Scaffold(
  appBar: AppBar(
    // TODO: Add buttons and title (102)
    leading: IconButton(
      icon: Icon(
        Icons.menu,
        semanticLabel: 'menu',
      ),
      onPressed: () {
        print('Menu button');
      },
    ),
```

should be:

```
return Scaffold(
  appBar: AppBar(
    // TODO: Add buttons and title (102)
    leading: IconButton(
      icon: Icon(
        Icons.menu,
        semanticLabel: 'menu',
        color: Colors.white, // added
      ),
      onPressed: () {
        print('Menu button');
      },
    ),
```

**Comment by michdud** [comment]
Hi there,
Thanks for reporting this! Is the icon currently a color other than white for you? I ran the codelab again with the latest version of Flutter, and it seems like the default is still a white icon. 

Is there any chance you have some theming that could be interfering with the color of icon?
Thanks!

**Comment by willlarche** [comment]
I'm going to close this. Feel free to reopen it if you see this issue again.
